#!/usr/bin/env python3
"""Generate all app icons from assets/branding/notepad-pro.svg.

Regeneration requires ImageMagick (convert or magick); --check uses only Python's
standard library and verifies generated resources, raster hashes and dimensions.
The build consumes checked-in assets, so ImageMagick is not a build dependency.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import struct
import subprocess
import tempfile
import xml.etree.ElementTree as ET
from xml.sax.saxutils import quoteattr

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets/branding/notepad-pro.svg"
MANIFEST = ROOT / "assets/branding/generated-icons.json"
ANDROID = "http://schemas.android.com/apk/res/android"
SVG = "http://www.w3.org/2000/svg"
RES = "androidApp/src/main/res"
ICO = "desktopApp/src/main/resources/icons/notepad-pro.ico"
ICO_SIZES = (16, 20, 24, 32, 40, 48, 64, 128, 256)
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
PNG_SIZES = {"assets/branding/notepad-pro.png": 512}
for density, size in DENSITIES.items():
    for name in ("ic_launcher", "ic_launcher_round"):
        PNG_SIZES[f"{RES}/mipmap-{density}/{name}.png"] = size
GENERATED = "<!-- Generated by tools/generate_icons.py; edit assets/branding/notepad-pro.svg. -->\n"


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def artwork() -> tuple[list[ET.Element], list[ET.Element]]:
    root = ET.parse(SOURCE).getroot()
    assert root.get("viewBox") == "0 0 512 512"
    background = root.find(f"{{{SVG}}}g[@id='background']")
    mark = root.find(f"{{{SVG}}}g[@id='mark']")
    assert background is not None and mark is not None
    paths = list(background) + list(mark)
    assert all(p.tag == f"{{{SVG}}}path" and p.get("fill") and p.get("d") for p in paths)
    return list(background), list(mark)


def vector_path(path: ET.Element, indent: str = "    ") -> str:
    return f'{indent}<path android:fillColor={quoteattr(path.attrib["fill"])} android:pathData={quoteattr(path.attrib["d"])}/>\n'


def vector(body: str, size: int) -> str:
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n' + GENERATED
        + f'<vector xmlns:android="{ANDROID}" android:width="{size}dp" android:height="{size}dp" '
        + f'android:viewportWidth="{size}" android:viewportHeight="{size}">\n'
        + body + '</vector>\n'
    )


def generated_text() -> dict[str, str]:
    background, mark = artwork()
    full = "".join(vector_path(p) for p in background + mark)
    # Fit every essential part inside the adaptive icon's 66dp safe-zone circle.
    group = '    <group android:scaleX="0.16" android:scaleY="0.16" android:translateX="13.04" android:translateY="13.04">\n'
    foreground = group + "".join(vector_path(p, "        ") for p in mark) + '    </group>\n'
    by_id = {p.attrib["id"]: p for p in mark}
    holes = " ".join(by_id[name].attrib["d"] for name in ("paper", "fold", "rule-1", "rule-2", "rule-3"))
    monochrome = group + (
        '        <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" '
        + f'android:pathData={quoteattr(holes)}/>\n'
    )
    for name in ("pencil-cap", "pencil-body", "pencil-tip"):
        monochrome += f'        <path android:fillColor="#FFFFFFFF" android:pathData={quoteattr(by_id[name].attrib["d"])}/>\n'
    monochrome += '    </group>\n'
    result = {
        "shared/src/commonMain/composeResources/drawable/notepad_pro.xml": vector(full, 512),
        f"{RES}/drawable/ic_launcher_foreground.xml": vector(foreground, 108),
        f"{RES}/drawable/ic_launcher_monochrome.xml": vector(monochrome, 108),
        f"{RES}/values/icon_colors.xml": (
            '<?xml version="1.0" encoding="utf-8"?>\n' + GENERATED
            + '<resources>\n    <color name="ic_launcher_background">'
            + background[0].attrib["fill"] + '</color>\n</resources>\n'
        ),
    }
    for api in (26, 33):
        adaptive = (
            '<?xml version="1.0" encoding="utf-8"?>\n' + GENERATED
            + f'<adaptive-icon xmlns:android="{ANDROID}">\n'
            + '    <background android:drawable="@color/ic_launcher_background"/>\n'
            + '    <foreground android:drawable="@drawable/ic_launcher_foreground"/>\n'
        )
        if api >= 33:
            adaptive += '    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n'
        adaptive += '</adaptive-icon>\n'
        for name in ("ic_launcher", "ic_launcher_round"):
            result[f"{RES}/mipmap-anydpi-v{api}/{name}.xml"] = adaptive
    return result


def generate() -> None:
    convert = shutil.which("magick") or shutil.which("convert")
    if convert is None:
        raise SystemExit("Install ImageMagick to regenerate icons; --check does not require it.")
    for path, text in generated_text().items():
        destination = ROOT / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(text, encoding="utf-8")
    with tempfile.TemporaryDirectory(prefix="notepad-icons-") as directory:
        temp = Path(directory)
        background, mark = artwork()
        circle = ET.Element("path", {
            "fill": background[0].attrib["fill"],
            "d": "M256 0A256 256 0 1 1 256 512A256 256 0 1 1 256 0Z",
        })
        # Render the SVG's solid paths directly. This also works on ImageMagick
        # installations without an optional librsvg/rsvg-convert delegate.
        for paths, name in ((background + mark, "square.png"), ([circle] + mark, "round.png")):
            drawing = "scale 4,4 stroke none " + " ".join(
                f"fill '{path.attrib['fill']}' path '{path.attrib['d']}'" for path in paths
            )
            subprocess.run([convert, "-size", "2048x2048", "xc:none", "-draw", drawing,
                            "-resize", "1024x1024", "-strip", f"PNG32:{temp / name}"], check=True)
        for path, size in PNG_SIZES.items():
            destination = ROOT / path
            destination.parent.mkdir(parents=True, exist_ok=True)
            source = temp / ("round.png" if "ic_launcher_round" in path else "square.png")
            subprocess.run([convert, str(source), "-resize", f"{size}x{size}", "-strip",
                            "-define", "png:exclude-chunks=date,time", f"PNG32:{destination}"], check=True)
        destination = ROOT / ICO
        destination.parent.mkdir(parents=True, exist_ok=True)
        sizes = ",".join(str(s) for s in reversed(ICO_SIZES))
        subprocess.run([convert, str(temp / "square.png"), "-define", f"icon:auto-resize={sizes}",
                        str(destination)], check=True)
    # Normalize source line endings so --check also works on Windows checkouts.
    manifest = {
        "source": SOURCE.relative_to(ROOT).as_posix(),
        "sourceSha256": digest(SOURCE.read_text(encoding="utf-8").encode("utf-8")),
        "rasters": {path: digest((ROOT / path).read_bytes()) for path in sorted([*PNG_SIZES, ICO])},
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Generated {len(generated_text())} XML resources, {len(PNG_SIZES)} PNGs and one multi-size ICO.")


def check() -> None:
    for path, text in generated_text().items():
        assert (ROOT / path).read_text(encoding="utf-8") == text, f"Stale generated resource: {path}"
        ET.fromstring(text)
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    assert manifest["sourceSha256"] == digest(SOURCE.read_text(encoding="utf-8").encode("utf-8")), "Regenerate icons after changing the SVG."
    assert set(manifest["rasters"]) == {*PNG_SIZES, ICO}
    for path, expected in manifest["rasters"].items():
        assert digest((ROOT / path).read_bytes()) == expected, f"Modified raster: {path}; regenerate icons."
    for path, size in PNG_SIZES.items():
        png = (ROOT / path).read_bytes()
        assert png[:8] == b"\x89PNG\r\n\x1a\n", path
        assert struct.unpack(">II", png[16:24]) == (size, size), f"Incorrect PNG dimensions: {path}"
        assert png[24:26] == bytes((8, 6)), f"Expected 8-bit RGBA PNG: {path}"
    ico = (ROOT / ICO).read_bytes()
    reserved, image_type, count = struct.unpack_from("<HHH", ico)
    assert (reserved, image_type, count) == (0, 1, len(ICO_SIZES)), "Invalid Windows ICO header."
    actual_sizes = set()
    for index in range(count):
        width, height, _, _, _, depth, length, offset = struct.unpack_from("<BBBBHHII", ico, 6 + index * 16)
        actual_sizes.add(width or 256)
        assert (width or 256) == (height or 256) and depth == 32
        assert length > 0 and offset >= 6 + count * 16 and offset + length <= len(ico)
    assert actual_sizes == set(ICO_SIZES), "Missing Windows icon sizes."
    app = ET.parse(ROOT / "androidApp/src/main/AndroidManifest.xml").getroot().find("application")
    assert app is not None
    assert app.get(f"{{{ANDROID}}}icon") == "@mipmap/ic_launcher", "Android launcher icon is not wired."
    assert app.get(f"{{{ANDROID}}}roundIcon") == "@mipmap/ic_launcher_round", "Android round icon is not wired."
    print("Icon checks passed: shared vector, Android legacy/adaptive/themed icons, and Windows ICO (16–256px).")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate checked-in assets without ImageMagick.")
    args = parser.parse_args()
    if args.check:
        check()
    else:
        generate()
